export const CREATE_GAME = 'CREATE_GAME'
export const FETCH_GAME = 'FETCH_GAME'
export const FETCH_ALL_GAMES = 'FETCH_ALL_GAMES'
export const START_GAME = 'START_GAME'
export const TMP_SCORE = 'TMP_SCORE'
export const UPDATE_SCORE = 'UPDATE_SCORE'
export const APPLY_ACTION = 'APPLY_ACTION'
export const ADD_IAE = 'ADD_IAE'
export const END_GAME = 'END_GAME'
export const ADD_CARD_EVENTS = 'ADD_CARD_EVENTS'

export const GET_ERRORS = 'GET_ERRORS'
