const actions = [
  {
    numCard: 1,
    cardPicture: '',
    title: 'Achat de matériel agricole',
    environnementEffect: -10,
    productionEffect: -20,
    tempsTravailEffect: 20,
    ancrageSocialEffect: 10,
    environnementCondition: 0,
    productionCondition: 0,
    tempsTravailCondition: 0,
    ancrageSocialCondition: 0
  },
  {
    numCard: 2,
    cardPicture: '',
    title: 'Allongement de la rotation',
    environnementEffect: 10,
    productionEffect: 20,
    tempsTravailEffect: -5,
    ancrageSocialEffect: 0,
    environnementCondition: 20,
    productionCondition: 0,
    tempsTravailCondition: 0,
    ancrageSocialCondition: 0
  },
  {
    numCard: 3,
    cardPicture: '',
    title: 'Augmentation du cheptel',
    environnementEffect: 0,
    productionEffect: -30,
    tempsTravailEffect: -15,
    ancrageSocialEffect: 0,
    environnementCondition: 0,
    productionCondition: 30,
    tempsTravailCondition: 0,
    ancrageSocialCondition: 0
  },
  {
    numCard: 4,
    cardPicture: '',
    title: 'Développement de l\'agrotourisme',
    environnementEffect: 0,
    productionEffect: 20,
    tempsTravailEffect: -20,
    ancrageSocialEffect: 0,
    environnementCondition: 0,
    productionCondition: 0,
    tempsTravailCondition: 0,
    ancrageSocialCondition: 30
  },
  {
    numCard: 5,
    cardPicture: '',
    title: 'Introduction du non travail du sol',
    environnementEffect: 15,
    productionEffect: -5,
    tempsTravailEffect: 15,
    ancrageSocialEffect: 0,
    environnementCondition: 0,
    productionCondition: 30,
    tempsTravailCondition: 0,
    ancrageSocialCondition: 0
  },
  {
    numCard: 6,
    cardPicture: '',
    title: 'Nouvelle subvention pour l\'envrionnement',
    environnementEffect: 0,
    productionEffect: 10,
    tempsTravailEffect: 0,
    ancrageSocialEffect: -5,
    environnementCondition: 30,
    productionCondition: 0,
    tempsTravailCondition: 0,
    ancrageSocialCondition: 0
  },
  {
    numCard: 7,
    cardPicture: '',
    title: 'Embauche d\'un salarié',
    environnementEffect: 0,
    productionEffect: -20,
    tempsTravailEffect: 30,
    ancrageSocialEffect: 10,
    environnementCondition: 0,
    productionCondition: 0,
    tempsTravailCondition: 0,
    ancrageSocialCondition: 0
  },
  {
    numCard: 8,
    cardPicture: '',
    title: 'Partage du territoire agricole',
    environnementEffect: 0,
    productionEffect: -5,
    tempsTravailEffect: 5,
    ancrageSocialEffect: 15,
    environnementCondition: 0,
    productionCondition: 10,
    tempsTravailCondition: 0,
    ancrageSocialCondition: 0
  }
]
